ignorePatterns:
  - node_modules
  - public
  - "**/*.js"

plugins:
  - react
  - react-hooks
  - "@typescript-eslint"

extends:
  - airbnb-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended

parserOptions:
  project:
    - ./tsconfig.json
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: latest
  import/resolver:
    node:
      paths:
        - src

rules:
  arrow-body-style:
    - warn
    - as-needed
  no-prototype-builtins: off
  operator-linebreak: off
  implicit-arrow-linebreak: off
  no-shadow: off
  "@typescript-eslint/no-shadow": warn
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  max-len:
    - warn
    - code: 160
  indent: off
  "@typescript-eslint/indent":
    - warn
    - 4
    - SwitchCase: 1
      ignoredNodes:
        - JSXElement
        - JSXElement > *
        - JSXAttribute
        - JSXIdentifier
        - JSXNamespacedName
        - JSXMemberExpression
        - JSXSpreadAttribute
        - JSXExpressionContainer
        - JSXOpeningElement
        - JSXClosingElement
        - JSXText
        - JSXEmptyExpression
        - JSXSpreadChil
  "@typescript-eslint/no-unused-expressions":
    - error
    - allowShortCircuit: true
      allowTernary: true
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
      allowTypedFunctionExpressions: true
  "@typescript-eslint/ban-types": warn
  react/jsx-no-bind: off
  react/no-direct-mutation-state: error
  react/no-access-state-in-setstate: warn
  react/destructuring-assignment: off
  react/jsx-tag-spacing: off
  react/sort-comp: off
  react/jsx-curly-brace-presence: off
  react/prefer-stateless-function: warn
  react/jsx-closing-bracket-location: off
  react/no-array-index-key: warn
  react/no-did-update-set-state: warn
  react/prop-types: off
  react/jsx-one-expression-per-line: off
  react/jsx-indent:
    - error
    - 4
  react/jsx-indent-props:
    - error
    - 4
  react/jsx-boolean-value:
    - warn
    - always
  react/jsx-props-no-spreading: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
