version: 2

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - make frontend
    - go mod tidy
builds:
  - main: ./
    id: hub
    binary: hub
    ldflags:
      - -X github.com/fsuhrau/automationhub/hub.version={{.Version}}
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64

  - main: ./cli
    id: hubcli
    binary: hubcli
    ldflags:
      - -X github.com/fsuhrau/automationhub/hub.version={{.Version}}
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64

brews:
  - name: automationhub
    directory: Formula
    repository:
      owner: fsuhrau
      name: homebrew-tap
      branch: master
    caveats: "hub configure # to get started"
    homepage: "https://github.com/fsuhrau/automationhub"
    description: "Automation Environment to run Unity3D PlayMode tests on real devices
      for android support install adb and aapt:
      brew install --cask android-commandlinetools"
#    dependencies:
#      - name: android-commandlinetools
