// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: action.proto

package action

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DeviceInteractionType int32

const (
	DeviceInteractionType_IsAppInstalled DeviceInteractionType = 0
	DeviceInteractionType_InstallApp     DeviceInteractionType = 1
	DeviceInteractionType_UninstallApp   DeviceInteractionType = 2
	DeviceInteractionType_StartApp       DeviceInteractionType = 3
	DeviceInteractionType_StopApp        DeviceInteractionType = 4
	DeviceInteractionType_IsAppConnected DeviceInteractionType = 5
	DeviceInteractionType_StartRecording DeviceInteractionType = 6
	DeviceInteractionType_StopRecording  DeviceInteractionType = 7
	DeviceInteractionType_HasFeature     DeviceInteractionType = 8
	DeviceInteractionType_ExecuteFeature DeviceInteractionType = 9
	DeviceInteractionType_GetScreenShopt DeviceInteractionType = 10
)

// Enum value maps for DeviceInteractionType.
var (
	DeviceInteractionType_name = map[int32]string{
		0:  "IsAppInstalled",
		1:  "InstallApp",
		2:  "UninstallApp",
		3:  "StartApp",
		4:  "StopApp",
		5:  "IsAppConnected",
		6:  "StartRecording",
		7:  "StopRecording",
		8:  "HasFeature",
		9:  "ExecuteFeature",
		10: "GetScreenShopt",
	}
	DeviceInteractionType_value = map[string]int32{
		"IsAppInstalled": 0,
		"InstallApp":     1,
		"UninstallApp":   2,
		"StartApp":       3,
		"StopApp":        4,
		"IsAppConnected": 5,
		"StartRecording": 6,
		"StopRecording":  7,
		"HasFeature":     8,
		"ExecuteFeature": 9,
		"GetScreenShopt": 10,
	}
)

func (x DeviceInteractionType) Enum() *DeviceInteractionType {
	p := new(DeviceInteractionType)
	*p = x
	return p
}

func (x DeviceInteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceInteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[0].Descriptor()
}

func (DeviceInteractionType) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[0]
}

func (x DeviceInteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceInteractionType.Descriptor instead.
func (DeviceInteractionType) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{0}
}

type ActionType int32

const (
	ActionType_Custom             ActionType = 0
	ActionType_GetSceneGraph      ActionType = 1
	ActionType_ElementIsDisplayed ActionType = 2
	ActionType_ElementSetValue    ActionType = 3
	ActionType_ElementGetValue    ActionType = 4
	ActionType_Move               ActionType = 5
	ActionType_TouchDown          ActionType = 6
	ActionType_TouchMove          ActionType = 7
	ActionType_TouchUp            ActionType = 8
	ActionType_DragAndDrop        ActionType = 9
	ActionType_LongTouch          ActionType = 10
	ActionType_ElementTouch       ActionType = 11
	ActionType_GetScreenshot      ActionType = 12
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0:  "Custom",
		1:  "GetSceneGraph",
		2:  "ElementIsDisplayed",
		3:  "ElementSetValue",
		4:  "ElementGetValue",
		5:  "Move",
		6:  "TouchDown",
		7:  "TouchMove",
		8:  "TouchUp",
		9:  "DragAndDrop",
		10: "LongTouch",
		11: "ElementTouch",
		12: "GetScreenshot",
	}
	ActionType_value = map[string]int32{
		"Custom":             0,
		"GetSceneGraph":      1,
		"ElementIsDisplayed": 2,
		"ElementSetValue":    3,
		"ElementGetValue":    4,
		"Move":               5,
		"TouchDown":          6,
		"TouchMove":          7,
		"TouchUp":            8,
		"DragAndDrop":        9,
		"LongTouch":          10,
		"ElementTouch":       11,
		"GetScreenshot":      12,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1}
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manager                string `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	DeviceId               string `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Name                   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OperationSystem        string `protobuf:"bytes,4,opt,name=OperationSystem,proto3" json:"OperationSystem,omitempty"`
	SupportedArchitectures string `protobuf:"bytes,5,opt,name=SupportedArchitectures,proto3" json:"SupportedArchitectures,omitempty"`
	Status                 string `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetOperationSystem() string {
	if x != nil {
		return x.OperationSystem
	}
	return ""
}

func (x *Device) GetSupportedArchitectures() string {
	if x != nil {
		return x.SupportedArchitectures
	}
	return ""
}

func (x *Device) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequest.ProtoReflect.Descriptor instead.
func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{1}
}

type DeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devices []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *DeviceResponse) Reset() {
	*x = DeviceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceResponse) ProtoMessage() {}

func (x *DeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceResponse.ProtoReflect.Descriptor instead.
func (*DeviceResponse) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type InteractionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type DeviceInteractionType `protobuf:"varint,1,opt,name=type,proto3,enum=action.DeviceInteractionType" json:"type,omitempty"`
}

func (x *InteractionRequest) Reset() {
	*x = InteractionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionRequest) ProtoMessage() {}

func (x *InteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionRequest.ProtoReflect.Descriptor instead.
func (*InteractionRequest) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{3}
}

func (x *InteractionRequest) GetType() DeviceInteractionType {
	if x != nil {
		return x.Type
	}
	return DeviceInteractionType_IsAppInstalled
}

type InteractionRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InteractionRespone) Reset() {
	*x = InteractionRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractionRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionRespone) ProtoMessage() {}

func (x *InteractionRespone) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionRespone.ProtoReflect.Descriptor instead.
func (*InteractionRespone) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{4}
}

type SetAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attr string `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	Val  string `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *SetAttr) Reset() {
	*x = SetAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttr) ProtoMessage() {}

func (x *SetAttr) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttr.ProtoReflect.Descriptor instead.
func (*SetAttr) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{5}
}

func (x *SetAttr) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetAttr) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

func (x *SetAttr) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type GetAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attr string `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *GetAttr) Reset() {
	*x = GetAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttr) ProtoMessage() {}

func (x *GetAttr) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttr.ProtoReflect.Descriptor instead.
func (*GetAttr) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{6}
}

func (x *GetAttr) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAttr) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

type MoveOffset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   int64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *MoveOffset) Reset() {
	*x = MoveOffset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveOffset) ProtoMessage() {}

func (x *MoveOffset) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveOffset.ProtoReflect.Descriptor instead.
func (*MoveOffset) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{7}
}

func (x *MoveOffset) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *MoveOffset) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type MoveElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *MoveElement) Reset() {
	*x = MoveElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveElement) ProtoMessage() {}

func (x *MoveElement) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveElement.ProtoReflect.Descriptor instead.
func (*MoveElement) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{8}
}

func (x *MoveElement) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MoveElement) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type Touch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Xoffset int64  `protobuf:"varint,2,opt,name=xoffset,proto3" json:"xoffset,omitempty"`
	Yoffset int64  `protobuf:"varint,3,opt,name=yoffset,proto3" json:"yoffset,omitempty"`
}

func (x *Touch) Reset() {
	*x = Touch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Touch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Touch) ProtoMessage() {}

func (x *Touch) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Touch.ProtoReflect.Descriptor instead.
func (*Touch) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{9}
}

func (x *Touch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Touch) GetXoffset() int64 {
	if x != nil {
		return x.Xoffset
	}
	return 0
}

func (x *Touch) GetYoffset() int64 {
	if x != nil {
		return x.Yoffset
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionType ActionType `protobuf:"varint,1,opt,name=actionType,proto3,enum=action.ActionType" json:"actionType,omitempty"`
	// Types that are assignable to Payload:
	//	*Request_Id
	//	*Request_Data
	//	*Request_SetAttr
	//	*Request_GetAttr
	//	*Request_MoveOffset
	//	*Request_Touch
	//	*Request_MoveElement
	Payload isRequest_Payload `protobuf_oneof:"payload"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{10}
}

func (x *Request) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_Custom
}

func (m *Request) GetPayload() isRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Request) GetId() string {
	if x, ok := x.GetPayload().(*Request_Id); ok {
		return x.Id
	}
	return ""
}

func (x *Request) GetData() string {
	if x, ok := x.GetPayload().(*Request_Data); ok {
		return x.Data
	}
	return ""
}

func (x *Request) GetSetAttr() *SetAttr {
	if x, ok := x.GetPayload().(*Request_SetAttr); ok {
		return x.SetAttr
	}
	return nil
}

func (x *Request) GetGetAttr() *GetAttr {
	if x, ok := x.GetPayload().(*Request_GetAttr); ok {
		return x.GetAttr
	}
	return nil
}

func (x *Request) GetMoveOffset() *MoveOffset {
	if x, ok := x.GetPayload().(*Request_MoveOffset); ok {
		return x.MoveOffset
	}
	return nil
}

func (x *Request) GetTouch() *Touch {
	if x, ok := x.GetPayload().(*Request_Touch); ok {
		return x.Touch
	}
	return nil
}

func (x *Request) GetMoveElement() *MoveElement {
	if x, ok := x.GetPayload().(*Request_MoveElement); ok {
		return x.MoveElement
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

type Request_Data struct {
	Data string `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Request_SetAttr struct {
	SetAttr *SetAttr `protobuf:"bytes,4,opt,name=setAttr,proto3,oneof"`
}

type Request_GetAttr struct {
	GetAttr *GetAttr `protobuf:"bytes,5,opt,name=getAttr,proto3,oneof"`
}

type Request_MoveOffset struct {
	MoveOffset *MoveOffset `protobuf:"bytes,6,opt,name=moveOffset,proto3,oneof"`
}

type Request_Touch struct {
	Touch *Touch `protobuf:"bytes,7,opt,name=touch,proto3,oneof"`
}

type Request_MoveElement struct {
	MoveElement *MoveElement `protobuf:"bytes,8,opt,name=moveElement,proto3,oneof"`
}

func (*Request_Id) isRequest_Payload() {}

func (*Request_Data) isRequest_Payload() {}

func (*Request_SetAttr) isRequest_Payload() {}

func (*Request_GetAttr) isRequest_Payload() {}

func (*Request_MoveOffset) isRequest_Payload() {}

func (*Request_Touch) isRequest_Payload() {}

func (*Request_MoveElement) isRequest_Payload() {}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID  string `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	SessionID string `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Version   string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{11}
}

func (x *Session) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *Session) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *Session) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Screenshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sceengraph []byte `protobuf:"bytes,1,opt,name=sceengraph,proto3" json:"sceengraph,omitempty"`
	Screenshot []byte `protobuf:"bytes,2,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
}

func (x *Screenshot) Reset() {
	*x = Screenshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Screenshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screenshot) ProtoMessage() {}

func (x *Screenshot) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screenshot.ProtoReflect.Descriptor instead.
func (*Screenshot) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{12}
}

func (x *Screenshot) GetSceengraph() []byte {
	if x != nil {
		return x.Sceengraph
	}
	return nil
}

func (x *Screenshot) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionType ActionType `protobuf:"varint,1,opt,name=actionType,proto3,enum=action.ActionType" json:"actionType,omitempty"`
	Success    bool       `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are assignable to Payload:
	//	*Response_Visible
	//	*Response_Data
	//	*Response_Value
	//	*Response_Screenshot
	//	*Response_Session
	Payload isResponse_Payload `protobuf_oneof:"payload"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_action_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{13}
}

func (x *Response) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_Custom
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *Response) GetPayload() isResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Response) GetVisible() bool {
	if x, ok := x.GetPayload().(*Response_Visible); ok {
		return x.Visible
	}
	return false
}

func (x *Response) GetData() []byte {
	if x, ok := x.GetPayload().(*Response_Data); ok {
		return x.Data
	}
	return nil
}

func (x *Response) GetValue() string {
	if x, ok := x.GetPayload().(*Response_Value); ok {
		return x.Value
	}
	return ""
}

func (x *Response) GetScreenshot() *Screenshot {
	if x, ok := x.GetPayload().(*Response_Screenshot); ok {
		return x.Screenshot
	}
	return nil
}

func (x *Response) GetSession() *Session {
	if x, ok := x.GetPayload().(*Response_Session); ok {
		return x.Session
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Visible struct {
	Visible bool `protobuf:"varint,3,opt,name=visible,proto3,oneof"`
}

type Response_Data struct {
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

type Response_Value struct {
	Value string `protobuf:"bytes,5,opt,name=value,proto3,oneof"`
}

type Response_Screenshot struct {
	Screenshot *Screenshot `protobuf:"bytes,6,opt,name=screenshot,proto3,oneof"`
}

type Response_Session struct {
	Session *Session `protobuf:"bytes,7,opt,name=session,proto3,oneof"`
}

func (*Response_Visible) isResponse_Payload() {}

func (*Response_Data) isResponse_Payload() {}

func (*Response_Value) isResponse_Payload() {}

func (*Response_Screenshot) isResponse_Payload() {}

func (*Response_Session) isResponse_Payload() {}

var File_action_proto protoreflect.FileDescriptor

var file_action_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xcc, 0x01, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x36, 0x0a, 0x16, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x22, 0x47, 0x0a, 0x12, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x65, 0x22, 0x3f, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x74, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76,
	0x61, 0x6c, 0x22, 0x2d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x74, 0x74,
	0x72, 0x22, 0x30, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x05, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x78, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x78, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x79, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x79, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x22, 0xe0, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x32, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x07, 0x73,
	0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x48, 0x00, 0x52,
	0x07, 0x73, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x48, 0x00, 0x52, 0x07, 0x67, 0x65,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x34, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x48, 0x00, 0x52,
	0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x74,
	0x6f, 0x75, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x48, 0x00, 0x52, 0x05, 0x74, 0x6f, 0x75,
	0x63, 0x68, 0x12, 0x37, 0x0a, 0x0b, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b,
	0x6d, 0x6f, 0x76, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x5d, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4c, 0x0a, 0x0a, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x65, 0x65, 0x6e, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x63, 0x65, 0x65, 0x6e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73,
	0x68, 0x6f, 0x74, 0x22, 0x90, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a,
	0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74,
	0x48, 0x00, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x2b,
	0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0xdb, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x0e, 0x49, 0x73, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x65, 0x64, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41,
	0x70, 0x70, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x41, 0x70, 0x70, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41,
	0x70, 0x70, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x70, 0x70, 0x10,
	0x04, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x73, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x74, 0x6f,
	0x70, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a,
	0x48, 0x61, 0x73, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x10, 0x08, 0x12, 0x12, 0x0a, 0x0e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x10, 0x09,
	0x12, 0x12, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x53, 0x68, 0x6f,
	0x70, 0x74, 0x10, 0x0a, 0x2a, 0xe7, 0x01, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x73, 0x44,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x10, 0x03, 0x12,
	0x13, 0x0a, 0x0f, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x10, 0x05, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x44, 0x6f, 0x77, 0x6e, 0x10, 0x06, 0x12, 0x0d, 0x0a,
	0x09, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07,
	0x54, 0x6f, 0x75, 0x63, 0x68, 0x55, 0x70, 0x10, 0x08, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x72, 0x61,
	0x67, 0x41, 0x6e, 0x64, 0x44, 0x72, 0x6f, 0x70, 0x10, 0x09, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x6f,
	0x6e, 0x67, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x10, 0x0a, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x10, 0x0b, 0x12, 0x11, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x10, 0x0c, 0x32, 0xda,
	0x01, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x41, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x4f, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x36, 0x0a, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x68,
	0x75, 0x62, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_action_proto_rawDescOnce sync.Once
	file_action_proto_rawDescData = file_action_proto_rawDesc
)

func file_action_proto_rawDescGZIP() []byte {
	file_action_proto_rawDescOnce.Do(func() {
		file_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_action_proto_rawDescData)
	})
	return file_action_proto_rawDescData
}

var file_action_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_action_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_action_proto_goTypes = []interface{}{
	(DeviceInteractionType)(0), // 0: action.DeviceInteractionType
	(ActionType)(0),            // 1: action.ActionType
	(*Device)(nil),             // 2: action.Device
	(*DeviceRequest)(nil),      // 3: action.DeviceRequest
	(*DeviceResponse)(nil),     // 4: action.DeviceResponse
	(*InteractionRequest)(nil), // 5: action.InteractionRequest
	(*InteractionRespone)(nil), // 6: action.InteractionRespone
	(*SetAttr)(nil),            // 7: action.SetAttr
	(*GetAttr)(nil),            // 8: action.GetAttr
	(*MoveOffset)(nil),         // 9: action.MoveOffset
	(*MoveElement)(nil),        // 10: action.MoveElement
	(*Touch)(nil),              // 11: action.Touch
	(*Request)(nil),            // 12: action.Request
	(*Session)(nil),            // 13: action.Session
	(*Screenshot)(nil),         // 14: action.Screenshot
	(*Response)(nil),           // 15: action.Response
}
var file_action_proto_depIdxs = []int32{
	2,  // 0: action.DeviceResponse.devices:type_name -> action.Device
	0,  // 1: action.InteractionRequest.type:type_name -> action.DeviceInteractionType
	1,  // 2: action.Request.actionType:type_name -> action.ActionType
	7,  // 3: action.Request.setAttr:type_name -> action.SetAttr
	8,  // 4: action.Request.getAttr:type_name -> action.GetAttr
	9,  // 5: action.Request.moveOffset:type_name -> action.MoveOffset
	11, // 6: action.Request.touch:type_name -> action.Touch
	10, // 7: action.Request.moveElement:type_name -> action.MoveElement
	1,  // 8: action.Response.actionType:type_name -> action.ActionType
	14, // 9: action.Response.screenshot:type_name -> action.Screenshot
	13, // 10: action.Response.session:type_name -> action.Session
	3,  // 11: action.RemoteDevice.DeviceList:input_type -> action.DeviceRequest
	5,  // 12: action.RemoteDevice.DeviceInteraction:input_type -> action.InteractionRequest
	12, // 13: action.RemoteDevice.ActionExecute:input_type -> action.Request
	4,  // 14: action.RemoteDevice.DeviceList:output_type -> action.DeviceResponse
	6,  // 15: action.RemoteDevice.DeviceInteraction:output_type -> action.InteractionRespone
	15, // 16: action.RemoteDevice.ActionExecute:output_type -> action.Response
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_action_proto_init() }
func file_action_proto_init() {
	if File_action_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InteractionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InteractionRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveOffset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Touch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Screenshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_action_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_action_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*Request_Id)(nil),
		(*Request_Data)(nil),
		(*Request_SetAttr)(nil),
		(*Request_GetAttr)(nil),
		(*Request_MoveOffset)(nil),
		(*Request_Touch)(nil),
		(*Request_MoveElement)(nil),
	}
	file_action_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*Response_Visible)(nil),
		(*Response_Data)(nil),
		(*Response_Value)(nil),
		(*Response_Screenshot)(nil),
		(*Response_Session)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_action_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_action_proto_goTypes,
		DependencyIndexes: file_action_proto_depIdxs,
		EnumInfos:         file_action_proto_enumTypes,
		MessageInfos:      file_action_proto_msgTypes,
	}.Build()
	File_action_proto = out.File
	file_action_proto_rawDesc = nil
	file_action_proto_goTypes = nil
	file_action_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RemoteDeviceClient is the client API for RemoteDevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteDeviceClient interface {
	DeviceList(ctx context.Context, opts ...grpc.CallOption) (RemoteDevice_DeviceListClient, error)
	DeviceInteraction(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (RemoteDevice_DeviceInteractionClient, error)
	ActionExecute(ctx context.Context, in *Request, opts ...grpc.CallOption) (RemoteDevice_ActionExecuteClient, error)
}

type remoteDeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteDeviceClient(cc grpc.ClientConnInterface) RemoteDeviceClient {
	return &remoteDeviceClient{cc}
}

func (c *remoteDeviceClient) DeviceList(ctx context.Context, opts ...grpc.CallOption) (RemoteDevice_DeviceListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RemoteDevice_serviceDesc.Streams[0], "/action.RemoteDevice/DeviceList", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteDeviceDeviceListClient{stream}
	return x, nil
}

type RemoteDevice_DeviceListClient interface {
	Send(*DeviceRequest) error
	Recv() (*DeviceResponse, error)
	grpc.ClientStream
}

type remoteDeviceDeviceListClient struct {
	grpc.ClientStream
}

func (x *remoteDeviceDeviceListClient) Send(m *DeviceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoteDeviceDeviceListClient) Recv() (*DeviceResponse, error) {
	m := new(DeviceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *remoteDeviceClient) DeviceInteraction(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (RemoteDevice_DeviceInteractionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RemoteDevice_serviceDesc.Streams[1], "/action.RemoteDevice/DeviceInteraction", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteDeviceDeviceInteractionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RemoteDevice_DeviceInteractionClient interface {
	Recv() (*InteractionRespone, error)
	grpc.ClientStream
}

type remoteDeviceDeviceInteractionClient struct {
	grpc.ClientStream
}

func (x *remoteDeviceDeviceInteractionClient) Recv() (*InteractionRespone, error) {
	m := new(InteractionRespone)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *remoteDeviceClient) ActionExecute(ctx context.Context, in *Request, opts ...grpc.CallOption) (RemoteDevice_ActionExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RemoteDevice_serviceDesc.Streams[2], "/action.RemoteDevice/ActionExecute", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteDeviceActionExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RemoteDevice_ActionExecuteClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type remoteDeviceActionExecuteClient struct {
	grpc.ClientStream
}

func (x *remoteDeviceActionExecuteClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RemoteDeviceServer is the server API for RemoteDevice service.
type RemoteDeviceServer interface {
	DeviceList(RemoteDevice_DeviceListServer) error
	DeviceInteraction(*InteractionRequest, RemoteDevice_DeviceInteractionServer) error
	ActionExecute(*Request, RemoteDevice_ActionExecuteServer) error
}

// UnimplementedRemoteDeviceServer can be embedded to have forward compatible implementations.
type UnimplementedRemoteDeviceServer struct {
}

func (*UnimplementedRemoteDeviceServer) DeviceList(RemoteDevice_DeviceListServer) error {
	return status.Errorf(codes.Unimplemented, "method DeviceList not implemented")
}
func (*UnimplementedRemoteDeviceServer) DeviceInteraction(*InteractionRequest, RemoteDevice_DeviceInteractionServer) error {
	return status.Errorf(codes.Unimplemented, "method DeviceInteraction not implemented")
}
func (*UnimplementedRemoteDeviceServer) ActionExecute(*Request, RemoteDevice_ActionExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method ActionExecute not implemented")
}

func RegisterRemoteDeviceServer(s *grpc.Server, srv RemoteDeviceServer) {
	s.RegisterService(&_RemoteDevice_serviceDesc, srv)
}

func _RemoteDevice_DeviceList_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteDeviceServer).DeviceList(&remoteDeviceDeviceListServer{stream})
}

type RemoteDevice_DeviceListServer interface {
	Send(*DeviceResponse) error
	Recv() (*DeviceRequest, error)
	grpc.ServerStream
}

type remoteDeviceDeviceListServer struct {
	grpc.ServerStream
}

func (x *remoteDeviceDeviceListServer) Send(m *DeviceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoteDeviceDeviceListServer) Recv() (*DeviceRequest, error) {
	m := new(DeviceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RemoteDevice_DeviceInteraction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InteractionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemoteDeviceServer).DeviceInteraction(m, &remoteDeviceDeviceInteractionServer{stream})
}

type RemoteDevice_DeviceInteractionServer interface {
	Send(*InteractionRespone) error
	grpc.ServerStream
}

type remoteDeviceDeviceInteractionServer struct {
	grpc.ServerStream
}

func (x *remoteDeviceDeviceInteractionServer) Send(m *InteractionRespone) error {
	return x.ServerStream.SendMsg(m)
}

func _RemoteDevice_ActionExecute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemoteDeviceServer).ActionExecute(m, &remoteDeviceActionExecuteServer{stream})
}

type RemoteDevice_ActionExecuteServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type remoteDeviceActionExecuteServer struct {
	grpc.ServerStream
}

func (x *remoteDeviceActionExecuteServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _RemoteDevice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "action.RemoteDevice",
	HandlerType: (*RemoteDeviceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DeviceList",
			Handler:       _RemoteDevice_DeviceList_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DeviceInteraction",
			Handler:       _RemoteDevice_DeviceInteraction_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ActionExecute",
			Handler:       _RemoteDevice_ActionExecute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "action.proto",
}
